name: teklub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 10.0.0+10

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0
  adaptive_dialog: ^1.3.0
  keyboard_dismisser: ^2.0.0
  mask_text_input_formatter: ^2.1.0
  flutter_keyboard_visibility: ^5.1.1
  custom_check_box: ^0.0.4
  line_icons: ^2.0.1
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  get_storage: ^2.0.3
  http: ^0.13.4
  cherry_toast: 1.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  file_picker: ^4.3.3
  syncfusion_flutter_pdfviewer: ^19.4.50-beta
  flutter_html: ^2.2.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  qr_code_scanner: ^1.0.1
  #qr_mobile_vision: ^4.0.1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0
  flutter_fcm: ^0.0.12
  pull_to_refresh: ^2.0.0
  loadmore: ^2.0.1
  lazy_load_scrollview: ^1.3.0
  sizer: ^2.0.15
  youtube_player_iframe: ^2.2.2
  percent_indicator: 4.0.0
  equatable: ^2.0.3
  confetti: ^0.6.0
  flip_card: ^0.6.0
  dropdown_button2: ^1.4.0
  path_provider: ^2.0.10
  dio: ^4.0.6
#  permission_handler: ^9.2.0
  appmetrica_plugin: ^1.0.1
  image_save: ^5.0.0
  image_cropper: ^2.0.3
  rename: ^2.0.1
  clipboard: ^0.1.3
  # alice: ^0.2.0
  share_plus: ^4.5.0
  permission_handler: ^10.2.0
  open_file: ^3.2.1
  intl: ^0.18.1
  flutter_linkify: ^5.0.2
  image_picker: ^0.7.4
  flutter_image_compress: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: 2.0.5
#  flutter_launcher_name: "^0.0.1"

#flutter_launcher_name:
#  name: "PRYANIK ONLINE"


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon1.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/images/splash.png
  color: "131313"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Regular.ttf
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf

    - family: SFProTextMedium
      fonts:
        - asset: assets/fonts/SFProDisplay-Medium.ttf

    - family: SFProTextBold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf

    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Russo-One
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf

    - family: Arial
      fonts:
          - asset: assets/fonts/ARIAL.TTF
